[build]
buildCommand = "composer install --optimize-autoloader --no-scripts --no-interaction && npm run build"

[deploy]
startCommand = "php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --env=prod && php -S 0.0.0.0:$PORT -t public/"